### ISSUE TITLE
Automatic focus on name modal's input

### ISSUE THREAD

**Issue by mariogillazaro** [sabs231/wizecat#28]
Wizecatting would be faster if the name input was focused on page load.

**Comment by mafiuss** [comment]
Tried to fix this in https://github.com/sabs231/wizecat/blob/master/wizecatFrontend/src/wizecat-app/wizecat-app.html#L61 but don't seem to be working

**Comment by mafiuss** [comment]
Closing since we removed this functionality in #58.
