### ISSUE TITLE
Total time filter not working

### ISSUE THREAD

**Issue by mariogillazaro** [sabs231/wizecat#29]
## Expected behavior
`Time in shelter` table should show first the cats with the most accumulated time, regardless of the times it's been wizecatted.

## Observed behavior 👀 
`Time in shelter` table shows the same ordering as the `Times sheltered` table.

![screen shot 2018-01-22 at 3 17 02 pm](https://user-images.githubusercontent.com/31219005/35244881-564c6384-ff87-11e7-8132-b39f75d7b520.png)

**Comment by mafiuss** [comment]
Can you please review the current version in wize.cat, latest shameborad fixes may have fixed this, otherwise let me know

**Comment by julianlimon** [comment]
This is still happening. Please see this example

![screen shot 2018-01-24 at 11 35 06 am](https://user-images.githubusercontent.com/8528124/35347427-b560060e-00fa-11e8-93fc-67f1005bdae3.png)

**Comment by mafiuss** [comment]
@sabs231 ⬆️

**Comment by julianlimon** [comment]
Still not working
![screen shot 2018-01-26 at 1 17 56 pm](https://user-images.githubusercontent.com/8528124/35456715-1db37edc-029c-11e8-883e-44b2a132303c.png)
