### ISSUE TITLE
`Enter` to wizecat

### ISSUE THREAD

**Issue by julianlimon** [sabs231/wizecat#30]
Wizecatting would be faster if you could use the `Enter` key after you've entered the name of the person wizecatted. Currently, you need to use the mouse

**Comment by mafiuss** [comment]
Probably this is already fixed @julianlimon ? If so can you close, now we don't use input fields anymore

**Comment by mafiuss** [comment]
I´ll go ahead and close this, we are now using google sigin in, no more input field for entering the name so no longer need for this
