### ISSUE TITLE
Autofill name

### ISSUE THREAD

**Issue by julianlimon** [sabs231/wizecat#31]
As a prankster, I would like the name of the person I'm wizecatting to be pre-populated (if the person has been wizecatted on that computer before) so that I can prank faster. 

Acceptance criteria
- `Who are you wizecatting` is saved somewhere (a cookie? Chrome's autofill features?) o
- If there is saved data, `Who are you wizecatting?` is autofilled with the saved data

**Comment by mafiuss** [comment]
Will close because google signin flow fixed the "autofill" by sending automatically the user's email address 😉
