### ISSUE TITLE
Selectable list of users

### ISSUE THREAD

**Issue by julianlimon** [sabs231/wizecat#35]
As a prankster, I want to select the wizecatted user from a prepopulated list of names that includes all Wizeliners so I can prank the right person without repetitions. 

Acceptance criteria
- Only Wizeliners (by name, email or handle) can be selected.

**Comment by mafiuss** [comment]
@julianlimon I think this may be also deprecated with the new google signin? Can you review and close if needed? Thank you :)

**Comment by julianlimon** [comment]
Agree. We can remove this now.
