### ISSUE TITLE
Wizeline branding

### ISSUE THREAD

**Issue by julianlimon** [sabs231/wizecat#4]
As a pranked user, I want the prank to reflect use Wizeline colors and branding so that I recognize this as a Wizeline-sanctioned tool to remind employees of security awareness

Acceptance criteria:
- Follow https://projects.invisionapp.com/boards/P83B7VPKE9HSN/

**Comment by julianlimon** [comment]
I believe this is done. @mariogillazaro can you confirm?

**Comment by mariogillazaro** [comment]
@julianlimon I think it is

**Comment by julianlimon** [comment]
Awesome. Closed with #26
