### ISSUE TITLE
Update Gerrit's Wizecat response

### ISSUE THREAD

**Issue by wendywizeline** [sabs231/wizecat#47]
*TIME IN SHELTER*
1 - :sports_medal: *Benigni* has been Wizecatted for *4104.537* s and had *2* Wizecat lives

*Change to*
1 - :sports_medal: *name* has been Wizecatted for *mm:ss*

*TIMES SHELTERED*
1 - :sports_medal: *sabs* has been Wizecatted for *662.706* s and had *15* Wizecat lives

*Change to*
1 - :sports_medal: *name* has had *n* Wizecat lives

**Comment by mafiuss** [comment]
Fixed in https://github.com/wizeline/ws-bot/pull/37
