### ISSUE TITLE
Gerrit's "today" vs "this week" responses seem incorrect

### ISSUE THREAD

**Issue by wendywizeline** [sabs231/wizecat#48]
See image: https://cl.ly/2Y3N2W2R3u1Z

Why would this week show a time that was less than today?

**Comment by mafiuss** [comment]
@sabs231 can you take this?

**Comment by mafiuss** [comment]
I think here:
https://github.com/sabs231/wizecat/blob/72dfc04bb86157a7304d3e9eb0f342b82c3519b7/wizecatBackend/routes/shameboard.js#L12
If the filter is 'day' you get the day of the week number, monday = 1, tuesday = 2, but if you compare that with the current day number, you end up with all records of say, monday, or all tuesdays, I think thats a clue for this 🐞
