### ISSUE TITLE
Please add real-time notifications to slack

### ISSUE THREAD

**Issue by chitopunk** [sabs231/wizecat#70]
## Story
It would be great to have a dedicated channel in slack to receive notifications or maybe an RSS feed that publishes in real time who has been wizecatted..

## Acceptance criteria

Will warn users that are in the #wizecatted channel

* Users can go back quickly and lock their laptop
* less shame :D

**Comment by chitopunk** [comment]
When a user is wizecatted, the wize.cat app must publish the information in RSS/Atom feed or send a push notification to Slack

**Comment by mafiuss** [comment]
😎 I got this.
