### ISSUE TITLE
Wizeline-shelter: tag anonymous

### ISSUE THREAD

**Issue by wendywizeline** [sabs231/wizecat#79]
## Story
Make anonymous more fun

## Acceptance criteria
_List of conditions for the story to be accepted by its protagonist. e.g._
* Track users who are anonymous
* Update anonymous tracking with silly cat names from https://explodingkittens.com/cat-name-generator/
* Add time to anonymous depart

**Comment by mafiuss** [comment]
Will use https://www.npmjs.com/package/cat-names to to get random names
