### ISSUE TITLE
Prevent user hack the counter by Refreshing the page

### ISSUE THREAD

**Issue by vanduc1102** [sabs231/wizecat#98]
## Story
I can be on the top of the leaderboard by logged in and refresh the page many times.

## Acceptance criteria
- Counter should not increase when user refreshing the page.

## Sugesstions
- only increase Counter each 15 or 30 minutes.

**Comment by mafiuss** [comment]
just checking with you, there are two metrics
- time in shelter (time the page was open)
- times sheltered (times you visited the page)
The case you mention is the second, if you refresh the page it will count as a new connection thus as a new time in shelter, we could do what you suggest but AFAIK if someone wants to be on the top of the leaderboard by doing page refresh and increase their times been sheltered... well go ahead. That is my opinion @julianlimon @wendywizeline @sabs231 @mariogillazaro. Input?

**Comment by wendywizeline** [comment]
Yeah go ahead if you want to be top of the leaderboard... Keep refreshing.

**Comment by wendywizeline** [comment]
There's also the case where you step away from computer, someone WizeCats you, then you come back to close the window... repeat rapidly many times. Each of those times sheltered should be counted.

**Comment by wendywizeline** [comment]
Basically there shouldn't be the case where someone is rushing to be #1 most insecure laptop owner at Wizeline so ;)

**Comment by mafiuss** [comment]
Closing
